version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    command: mongod

volumes:
  mongodb_data:
